@echo off
echo Running rawfile2stream...
..\..\bin\rawfile2stream ..\..\Content2\media\thought.raw > thought.str
echo Running fir2...
..\..\Content2\03SignalProcessing\1Allman-FIR\fir2 ..\..\Content2\03SignalProcessing\1Allman-FIR\coefs.txt < thought.str > thought.fir
echo Running playstream.raw...
..\..\bin\playstream 1 44100 < thought.fir
exit
