#!/bin/sh
echo Running sox...
if [ $1 = "n" ] ; then
../../bin/sox -r 44100 -c 1 -w -s ../../Content2/media/thought.raw thought.wav
elif [ $1 = "r" ]; then
../../bin/sox -r 44100 -c 1 -w -s ../../Content2/media/thought.raw thought.wav reverb 1 800 400 200
fi
exit
